server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=zkeco
    username: yy
    password: 123qwe
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    datasource.max-active: 20
    datasource.max-idle: 8
    datasource.min-idle: 8
    datasource.initial-size: 10