server:
  port: 8090
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:sqlserver://localhost\SQLSERVER2016:1434;DatabaseName=zkeco
    username: sa
    password: 1
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    datasource.max-active: 20
    datasource.max-idle: 8
    datasource.min-idle: 8
    datasource.initial-size: 10